### ISSUE TITLE
Revert jshint to version 1.0.1

### ISSUE THREAD

**Issue by javieriserte** [fundacion-sadosky/genis#143]
Upgrading to 1.0.6 seems to work fine, it allows to use ECMAScript 6, the project compiles well, but a new problem appear while generating the distribution files. The problem was generated by the sbt-rjs plugin, no version of sbt-rjs allowed to finish the dist process right. 

This is the error to the version 1.0.9 (lastest of 1.x series) of sbt-rjs . and this is the discussion with the maintainers of rjs: https://github.com/sbt/sbt-rjs/issues/109

<code>
[info] Optimizing JavaScript with RequireJS
java.lang.IllegalArgumentException: Task scheduled with [32184000] seconds delay, which is too far in future, maximum delay is [21474835] seconds
        at akka.actor.LightArrayRevolverScheduler.checkMaxDelay(Scheduler.scala:327)
        at akka.actor.LightArrayRevolverScheduler.akka$actor$LightArrayRevolverScheduler$$schedule(Scheduler.scala:314)
        at akka.actor.LightArrayRevolverScheduler.scheduleOnce(Scheduler.scala:280)
        at akka.actor.Scheduler$class.scheduleOnce(Scheduler.scala:117)
        at akka.actor.LightArrayRevolverScheduler.scheduleOnce(Scheduler.scala:182)
        at akka.pattern.PromiseActorRef$.apply(AskSupport.scala:333)
        at akka.pattern.AskableActorRef$.ask$extension(AskSupport.scala:137)
        at akka.pattern.AskableActorRef$.$qmark$extension(AskSupport.scala:144)
        at com.typesafe.sbt.jse.SbtJsTask$.com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine(SbtJsTask.scala:185)
        at com.typesafe.sbt.jse.SbtJsTask$$anonfun$executeJs$1.apply(SbtJsTask.scala:427)
        at com.typesafe.sbt.jse.SbtJsTask$$anonfun$executeJs$1.apply(SbtJsTask.scala:422)
        at com.typesafe.sbt.web.SbtWeb$.withActorRefFactory(SbtWeb.scala:617)
        at com.typesafe.sbt.jse.SbtJsTask$.executeJs(SbtJsTask.scala:421)
        at com.typesafe.sbt.rjs.SbtRjs$$anonfun$runOptimizer$1$$anonfun$apply$9$$anonfun$8.apply(SbtRjs.scala:209)
        at com.typesafe.sbt.rjs.SbtRjs$$anonfun$runOptimizer$1$$anonfun$apply$9$$anonfun$8.apply(SbtRjs.scala:206)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at com.typesafe.sbt.rjs.SbtRjs$$anonfun$runOptimizer$1$$anonfun$apply$9.apply(SbtRjs.scala:222)
        at com.typesafe.sbt.rjs.SbtRjs$$anonfun$runOptimizer$1$$anonfun$apply$9.apply(SbtRjs.scala:191)
        at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
        at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
        at scala.Function$$anonfun$chain$1.apply(Function.scala:24)
        at com.typesafe.sbt.web.SbtWeb$$anonfun$projectSettings$49.apply(SbtWeb.scala:227)
        at com.typesafe.sbt.web.SbtWeb$$anonfun$projectSettings$49.apply(SbtWeb.scala:227)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
[error] (root/*:webPipeline) java.lang.IllegalArgumentException: Task scheduled with [32184000] seconds delay, which is too far in future, maximum delay is [21474835] seconds
[error] Total time: 94 s, completed 19/12/2024 17:50:10

</code>

**Comment by javieriserte** [comment]
Fixed in commit: [e4725f5](https://github.com/fundacion-sadosky/genis/commit/e4725f59cd94c0c444fe7cf9e4f0d29a22f6e5d2)
 ·
