### ISSUE TITLE
Random error akka.actor.OneForOneStrategy: empty.minBy

### ISSUE THREAD

**Issue by javieriserte** [fundacion-sadosky/genis#80]
[ERROR] 2023-12-04 01:30:03,118 [application-akka.actor.default-dispatcher-18] akka.actor.OneForOneStrategy: empty.minBy
java.lang.UnsupportedOperationException: empty.minBy
        at scala.collection.TraversableOnce$class.minBy(TraversableOnce.scala:254) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.collection.AbstractTraversable.minBy(Traversable.scala:104) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at user.RoleServiceImpl.translatePermission(RoleService.scala:66) ~[ar.org.fundacionsadosky.genis-5.1.9.jar:5.1.9]
        at audit.PeoOperationLogService$$anonfun$2.apply(OperationLogService.scala:75) ~[ar.org.fundacionsadosky.genis-5.1.9.jar:5.1.9
]
        at audit.PeoOperationLogService$$anonfun$2.apply(OperationLogService.scala:58) ~[ar.org.fundacionsadosky.genis-5.1.9.jar:5.1.9
]
        at audit.PEOSignerActor$$anonfun$logLotBehavior$1.applyOrElse(PEOSignerService.scala:64) ~[ar.org.fundacionsadosky.genis-5.1.9
.jar:5.1.9]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at audit.PEOSignerActor.aroundReceive(PEOSignerService.scala:50) ~[ar.org.fundacionsadosky.genis-5.1.9.jar:5.1.9]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-acto
r_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.11.jar:
na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.11.jar
:na]

**Comment by javieriserte** [comment]
The problem seems to be in the <code>translatePermission</code> method of the <code>RoleService</code> class.

The methods tries to get all valid operations that matches a given action and resource. The problem seems to be that for some case there is not such valid operation. The operations are collected into a set, and over that set the <code>.minBy</code> method is called. When the set is empty the error is thrown.

We can easily bypass this, but some some action might not be logged correctly. It'll be interesting to detect which action and resource is it trying to be logged and why the operation cannot be found.
